"""initial schema

Revision ID: b55e1e236c68
Revises: 
Create Date: 2026-09-25 01:29:07.971621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b55e1e236c68'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ok_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_cache'))
    )
    op.create_table('instance_settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_instance_settings'))
    )
    op.create_table('metric_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=120), nullable=False),
    sa.Column('metric', sa.String(length=80), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_points')),
    sa.UniqueConstraint('scope', 'metric', 'day', name=op.f('uq_metric_points_scope'))
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('name', name=op.f('uq_teams_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('admin', 'user', name='instancerole', native_enum=False, length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_breakglass', sa.Boolean(), nullable=False),
    sa.Column('locale', sa.Enum('de', 'en', name='locale', native_enum=False, length=40), nullable=False),
    sa.Column('color_mode', sa.Enum('auto', 'dark', 'light', name='colormode', native_enum=False, length=40), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=True),
    sa.Column('start_board_id', sa.Integer(), nullable=True),
    sa.Column('search_engine', sa.String(length=2000), nullable=True),
    sa.Column('prefs', sa.JSON(), nullable=False),
    sa.Column('totp_secret_enc', sa.LargeBinary(), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('recovery_codes', sa.JSON(), nullable=False),
    sa.Column('oidc_sub', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['start_board_id'], ['boards.id'], name=op.f('fk_users_start_board_id_boards'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], name=op.f('fk_users_theme_id_themes'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('oidc_sub', name=op.f('uq_users_oidc_sub'))
    )
    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=12), nullable=False),
    sa.Column('scope', sa.Enum('read', 'embed', name='tokenscope', native_enum=False, length=40), nullable=False),
    sa.Column('board_ids', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_api_tokens_token_hash'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_log_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_at'), ['at'], unique=False)

    op.create_table('invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='instancerole', native_enum=False, length=40), nullable=False),
    sa.Column('teams', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_invites_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invites')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_invites_token_hash'))
    )
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'editor', 'viewer', name='teamrole', native_enum=False, length=40), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_memberships_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('user_id', 'team_id', name=op.f('uq_memberships_user_id'))
    )
    op.create_table('notify_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url_enc', sa.LargeBinary(), nullable=False),
    sa.Column('min_severity', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notify_channels_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notify_channels'))
    )
    op.create_table('reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reset_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_reset_tokens_token_hash'))
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('password', 'oidc', 'token', name='authmethod', native_enum=False, length=40), nullable=False),
    sa.Column('csrf', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=300), nullable=False),
    sa.Column('pending_2fa', sa.Boolean(), nullable=False),
    sa.Column('id_token', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_sessions_token_hash'))
    )
    op.create_table('shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_kind', sa.Enum('space', 'board', 'widget', 'connection', 'theme', name='resourcekind', native_enum=False, length=40), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('grantee_kind', sa.Enum('user', 'team', name='granteekind', native_enum=False, length=40), nullable=False),
    sa.Column('grantee_id', sa.Integer(), nullable=False),
    sa.Column('right', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_shares_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shares')),
    sa.UniqueConstraint('resource_kind', 'resource_id', 'grantee_kind', 'grantee_id', name=op.f('uq_shares_resource_kind'))
    )
    op.create_table('spaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('personal', 'team', 'instance', name='spacekind', native_enum=False, length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_spaces_owner_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_spaces_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spaces')),
    sa.UniqueConstraint('owner_user_id', name=op.f('uq_spaces_owner_user_id')),
    sa.UniqueConstraint('team_id', name=op.f('uq_spaces_team_id'))
    )
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('service', sa.String(length=40), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('credential_mode', sa.Enum('shared', 'personal', name='credentialmode', native_enum=False, length=40), nullable=False),
    sa.Column('secret_enc', sa.LargeBinary(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('verify_tls', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_connections_space_id_spaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connections')),
    sa.UniqueConstraint('space_id', 'key', name=op.f('uq_connections_space_id'))
    )
    op.create_table('revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('board', 'widget', 'space', 'theme', name='revisionkind', native_enum=False, length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_revisions_space_id_spaces'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_revisions_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revisions'))
    )
    with op.batch_alter_table('revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revisions_entity_id'), ['entity_id'], unique=False)

    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('builtin', sa.Boolean(), nullable=False),
    sa.Column('contract', sa.Integer(), nullable=False),
    sa.Column('dark', sa.JSON(), nullable=False),
    sa.Column('light', sa.JSON(), nullable=False),
    sa.Column('custom_css', sa.Text(), nullable=False),
    sa.Column('fonts', sa.JSON(), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_themes_space_id_spaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_themes')),
    sa.UniqueConstraint('space_id', 'slug', name=op.f('uq_themes_space_id'))
    )
    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('min_team_role', sa.Enum('owner', 'editor', 'viewer', name='teamrole', native_enum=False, length=40), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_boards_space_id_spaces'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], name=op.f('fk_boards_theme_id_themes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boards')),
    sa.UniqueConstraint('space_id', 'slug', name=op.f('uq_boards_space_id'))
    )
    op.create_table('hints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('fingerprint', sa.String(length=200), nullable=False),
    sa.Column('rule', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=120), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('action_url', sa.String(length=2000), nullable=True),
    sa.Column('action_label', sa.String(length=120), nullable=True),
    sa.Column('due', sa.String(length=10), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], name=op.f('fk_hints_connection_id_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_hints_space_id_spaces'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_hints_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hints')),
    sa.UniqueConstraint('space_id', 'user_id', 'fingerprint', name=op.f('uq_hints_space_id'))
    )
    op.create_table('user_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('secret_enc', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], name=op.f('fk_user_credentials_connection_id_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_credentials_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_credentials')),
    sa.UniqueConstraint('connection_id', 'user_id', name=op.f('uq_user_credentials_connection_id'))
    )
    op.create_table('widgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('min_team_role', sa.Enum('owner', 'editor', 'viewer', name='teamrole', native_enum=False, length=40), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], name=op.f('fk_widgets_connection_id_connections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_widgets_space_id_spaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_widgets')),
    sa.UniqueConstraint('space_id', 'key', name=op.f('uq_widgets_space_id'))
    )
    op.create_table('hint_marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hint_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('open', 'snoozed', 'acknowledged', 'resolved', name='hintstate', native_enum=False, length=40), nullable=False),
    sa.Column('until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hint_id'], ['hints.id'], name=op.f('fk_hint_marks_hint_id_hints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_hint_marks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hint_marks')),
    sa.UniqueConstraint('hint_id', 'user_id', name=op.f('uq_hint_marks_hint_id'))
    )
    op.create_table('notify_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hint_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hint_id'], ['hints.id'], name=op.f('fk_notify_log_hint_id_hints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notify_log_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notify_log')),
    sa.UniqueConstraint('user_id', 'hint_id', name=op.f('uq_notify_log_user_id'))
    )
    op.create_table('overlays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name=op.f('fk_overlays_board_id_boards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_overlays_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_overlays')),
    sa.UniqueConstraint('user_id', 'board_id', name=op.f('uq_overlays_user_id'))
    )
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('cols', sa.Integer(), nullable=True),
    sa.Column('size', sa.Enum('small', 'medium', 'large', name='tilesize', native_enum=False, length=40), nullable=False),
    sa.Column('sort', sa.Enum('manual', 'alphabetical', name='sortorder', native_enum=False, length=40), nullable=False),
    sa.Column('collapsed', sa.Boolean(), nullable=False),
    sa.Column('area', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name=op.f('fk_sections_board_id_boards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sections'))
    )
    op.create_table('placements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('widget_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name=op.f('fk_placements_section_id_sections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['widget_id'], ['widgets.id'], name=op.f('fk_placements_widget_id_widgets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_placements'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('placements')
    op.drop_table('sections')
    op.drop_table('overlays')
    op.drop_table('notify_log')
    op.drop_table('hint_marks')
    op.drop_table('widgets')
    op.drop_table('user_credentials')
    op.drop_table('hints')
    op.drop_table('boards')
    op.drop_table('themes')
    with op.batch_alter_table('revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revisions_entity_id'))

    op.drop_table('revisions')
    op.drop_table('connections')
    op.drop_table('spaces')
    op.drop_table('shares')
    op.drop_table('sessions')
    op.drop_table('reset_tokens')
    op.drop_table('notify_channels')
    op.drop_table('memberships')
    op.drop_table('invites')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))

    op.drop_table('audit_log')
    op.drop_table('api_tokens')
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('metric_points')
    op.drop_table('instance_settings')
    op.drop_table('cache')
    # ### end Alembic commands ###
